IDDB = "SmpJbFhQdlpablRUbzlmc21saGdsOGlFTjB0bmc3OURYWHoxUVhvYQ=="
SIDDB = 'WC1QYXJzZS1BcHBsaWNhdGlvbi1JZA=='
SKDB = 'WC1QYXJzZS1SRVNULUFQSS1LZXk='
KDB = 'WVo5QzZ6TE5zTkNDM3lpUU5nQ2VLMFFlUzdrOHZodDlaaDhCSWcwbQ=='
EUL = 'aHR0cHM6Ly9hcGkucGFyc2UuY29tLzEvY2xhc3Nlcy9FcGlzb2Rl'
